version: "3.7"

services:
  kc-app:
    build: .
    ports:
      - "8081:8080"
    environment:
      KC_DB_URL: "jdbc:postgresql://kc-db:5432/keycloak"
      KC_DB_USERNAME: "db-user"
      KC_DB_PASSWORD: "db-password"
      KC_HOSTNAME: "localhost"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
  kc-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: "db-user"
      POSTGRES_PASSWORD: "db-password"
      POSTGRES_DB: "keycloak"
    expose:
      - "5432"